### PR TITLE
Automate release

### LINKED ISSUE #9: automate Monu.app releases
here's the algorithm:
- download atom-shell zip
- extract
- rename Atom.app to Monu.app
- copy entire contents of `monu` source folder into `Monu.app/Contents/Resources/app`
- rename CFBundleDisplayName, CFBundleIdentifier and CFBundleName fields in following plist files if they have these keys
- Atom.app/Contents/Info.plist
- Atom.app/Contents/Frameworks/Atom Helper.app/Contents/Info.plist
- test that the app works by double clicking it
- zip up Monu.app
- upload to github releases

### PR DESCRIPTION
**Pull request by remixz**
Fixes GH-9.

Now releases are super easy! :sparkles: Publishing instructions are in the README.

### CODE REVIEW

**Comment by remixz** [comment]
One note: The app code was moved into a new `app` folder to make it easier to create the executable, as otherwise it'd mean copying over each file individually, which would be messy, especially if someone forgot to add the new file to the makefile.

**Comment by max-mapper** [comment]
ah crap, just saw this. I was just doing this at the same time https://github.com/maxogden/atom-shell-packager

do you wanna update your makefile to run `npm run build` instead?

**Comment by remixz** [comment]
No worries! Your solution is much cleaner anyway, haha. Will do that.

**Comment by max-mapper** [comment]
@remixz also I am not sure it is necessary to move everything into an `app` folder. The only downside I see is that if you build the .app twice then the second one would include a copy of the first one, but we can fix that potential edge case by adding `--ignore=Monu.app` to the atom-shell-packager step.

I think your Makefile hackery was super cool, but I thought it would be another useful project for the atom-shell community to have an app packaging CLI tool, so I figured I'd bite the bullet and set the project up now. If I hadn't done that at the same time then I'd totally be cool using your Makefile portion

**Comment by remixz** [comment]
@maxogden Yeah, I just put it all into an app folder for ease of use with a Makefile, so I didn't have to muck around with temp folders. In JS though, much easier! :smile:

I've just updated the PR now (force pushed since there was some ugly history).

**Comment by max-mapper** [comment]
@remixz btw long term it would be cool to see you break the release stuff into a standalone release module :) but its probably better if we wait and use it for a while to get a sense of what features we would want in a standalone CLI (e.g. how abstract to make the API, vs how specific to atom apps to make it)

**Comment by max-mapper** [comment]
@remixz Just published this with `make publish`! https://github.com/maxogden/monu/releases/tag/v1.0.4

nanpcyp

**Pull request merged**
